export const PLACES = [
  "Ruaraka",
  "Gikomba",
  "Eldoret",
  "Likoni",
  "Ngong",
  "Juja",
  "Athi River",
  "Kitengela",
  "Naivasha",
  "Nyeri",
  "Thika",
  "Kamukunji",
  "Baba Dogo",
  "Kayole",
  "Pipeline",
  "Donholm",
  "Syokimau",
  "Ruiru",
  "Kikuyu",
  "Limuru",
  "Mlolongo",
  "Utawala",
  "Embakasi",
  "Eastleigh",
  "Huruma",
  "Kawangware",
  "Kangemi",
  "Uthiru",
  "Ruaka",
  "Ongata Rongai",
  "Nyali",
  "Changamwe",
  "Kondele Market",
  "Manyatta",
  "Milimani",
  "Lanet",
  "Njoro",
  "Mavoko",
  "Tala",
  "Kangundo",
] as const;

export const TRADES = [
  "Metal Works",
  "Fabricators",
  "Hardware",
  "Builders",
  "Enterprises",
  "Merchants",
  "Contractors",
  "Supplies",
  "Ventures",
  "Steel Works",
  "Joinery",
  "Roofing",
  "Tile Works",
  "Pipe Fitters",
  "Electrical",
  "Paint Works",
  "Cement Depot",
  "Door Works",
  "Window Works",
  "General Supplies",
] as const;

export const SUFFIXES = ["Ltd", "Co. Ltd", "Enterprises", "Group", "Self-Help Group"] as const;

export const FIRST_NAMES = [
  "Amina",
  "Peter",
  "Grace",
  "Daniel",
  "Faith",
  "Samuel",
  "Wanjiku",
  "Otieno",
  "Njeri",
  "Kiptoo",
  "Muthoni",
  "Barasa",
  "Omondi",
  "Chebet",
  "Kamau",
  "Achieng",
  "Mwangi",
  "Wambui",
  "Kipchoge",
  "Atieno",
  "Njoroge",
  "Wekesa",
  "Mutua",
  "Chepkoech",
  "Odhiambo",
  "Wairimu",
  "Kiprono",
  "Akinyi",
  "Kimani",
  "Nasieku",
] as const;

export const LAST_NAMES = [
  "Wanjiru",
  "Otieno",
  "Njeri",
  "Kiptoo",
  "Muthoni",
  "Barasa",
  "Kamau",
  "Omondi",
  "Chebet",
  "Mwangi",
  "Wambui",
  "Mutua",
  "Achieng",
  "Njoroge",
  "Wekesa",
  "Odhiambo",
  "Kimani",
  "Kiprono",
  "Wairimu",
  "Koech",
] as const;

export const PUBLIC_BODIES = [
  {
    id: "ent-state-housing",
    slug: "state-department-housing",
    legalName: "State Department for Housing and Urban Development",
    countyCode: "047",
  },
  {
    id: "ent-nairobi-planning",
    slug: "nairobi-city-county-planning",
    legalName: "Nairobi City County Planning Department",
    countyCode: "047",
  },
  {
    id: "ent-nca",
    slug: "national-construction-authority",
    legalName: "National Construction Authority",
    countyCode: "047",
  },
  {
    id: "ent-kebs",
    slug: "kenya-bureau-of-standards",
    legalName: "Kenya Bureau of Standards",
    countyCode: "047",
  },
  {
    id: "ent-msea",
    slug: "micro-and-small-enterprises-authority",
    legalName: "Micro and Small Enterprises Authority",
    countyCode: "047",
  },
  {
    id: "ent-ahb",
    slug: "affordable-housing-board",
    legalName: "Affordable Housing Board",
    countyCode: "047",
  },
  {
    id: "ent-kmrc",
    slug: "kenya-mortgage-refinance-company",
    legalName: "Kenya Mortgage Refinance Company",
    countyCode: "047",
  },
  {
    id: "ent-nakuru-housing",
    slug: "nakuru-county-housing-department",
    legalName: "Nakuru County Housing Department",
    countyCode: "032",
  },
] as const;

export const WARDS = [
  { id: "node-ward-embakasi-south", name: "Embakasi South", countyCode: "047" },
  { id: "node-ward-starehe", name: "Starehe", countyCode: "047" },
  { id: "node-ward-westlands", name: "Westlands", countyCode: "047" },
  { id: "node-ward-kasarani", name: "Kasarani", countyCode: "047" },
  { id: "node-ward-thika-town", name: "Thika Town", countyCode: "022" },
  { id: "node-ward-kiambu-town", name: "Kiambu Town", countyCode: "022" },
  { id: "node-ward-mashuuru", name: "Mashuuru", countyCode: "034" },
  { id: "node-ward-kitengela", name: "Kitengela", countyCode: "034" },
  { id: "node-ward-bondeni", name: "Bondeni", countyCode: "032" },
  { id: "node-ward-lanet", name: "Lanet", countyCode: "032" },
  { id: "node-ward-lumumba", name: "Migosi / Lumumba", countyCode: "042" },
  { id: "node-ward-kondele", name: "Kondele", countyCode: "042" },
  { id: "node-ward-stoni-athi", name: "Stoni Athi", countyCode: "016" },
  { id: "node-ward-athiriver", name: "Athi River", countyCode: "016" },
  { id: "node-ward-likoni", name: "Likoni", countyCode: "001" },
  { id: "node-ward-kapseret", name: "Kapseret", countyCode: "027" },
] as const;
